services:
  winconsorcios_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3431:4000' # API
      - '3432:6001' # WebSocket
    environment:
      DATABASE_URL: ${MONGO_URI}
    network_mode: bridge
